INSERT INTO `logement` (`id`, `Localisation`, `Nombre de voyageurs`, `Type de logement`, `Description`) VALUES
(1, 'Paris, Ile-de-France', 4, 'Appartement', 'Magnifique appartement au coeur de Paris. Comprend 2 salles de bain, 5 chambres, 1 cuisine et 1 balcon.'),
(2, 'Deauville, Basse Normandie', 3, 'Maison', 'Maison face à la mer.'),
(3, 'Nice, Provence-Alpes-Cotes-d''Azure', 2, 'Villa', 'Nouvel appartement dans la vieille ville de Nice à 2 minutes du cours Saleya et de la promenade des anglais. Il peut accueillir 4 personne, dispose d''une chambre en mezzanine ainsi que d''un canapé lit au salon. L''appartement vient d''être complètement refait, il dispose de la clim ainsi qu''internet.'),
(4, 'Strasbourg, Alsace', 2, 'Appartement', 'Charmant appartement au coeur de Strasbourg, à deux pas de la cathédrale, des marchés de noël, des musées, des boutiques et des meilleurs winstubs traditionnels. Ce 2 pièces est idéalement situé dans la zone piétonne du Carré d''Or.'),
(5, 'Lyon, Rhônes-Alpes', 4, 'Loft', 'Ancien atelier de soierie que j''ai réhabilité pour y vivre il y a deux ans dans un esprit \r\n"Loft" chaleureux,calme et épuré. Entierement équipé et doté de nombreux espaces de rangement,il constitue certainement un pied à terre idéal pour découvrir Lyon,de par son emplacement et son confort.'),
(6, 'Marseille, Provence-Alpes-Côte-d''Azure', 6, 'Maison', 'Votre logement au cœur de Marseille à la plaine dans une maison au calme avec jardin et terrasse.\r\nVous serez au cœur de la vie Marseillaise resto, café, galerie d''art et cinéma.. tout en étant au calme et profitez de l''accès facile au tram métro bus'),
(7, 'Nantes, Pays de la Loire', 4, 'Appartement', 'Appartement de 35 m² sur la butte Sainte Anne à Nantes dans une rue calme, à 5 minutes du centre ville. Transport en commun à proximité (Tram et bus). \r\nUne grande chambre et un salon/cuisine équipé. '),
(8, 'Toulouse, Midi-Pyrénées', 2, 'Appartement', 'L''appartement se situe à 3min du metro Compans, à 10 min de la place du Capitole. \r\nIdéalement situé pour un point de départ à la découverte de la ville rose. Je serais ravi de vous indiquer les endroits à voir et à vous faire partager mon expérience');
