-- MySQL Script generated by MySQL Workbench
-- 01/16/15 15:34:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema welchome
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema welchome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `welchome` DEFAULT CHARACTER SET latin1 ;
USE `welchome` ;

-- -----------------------------------------------------
-- Table `welchome`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`users` (
  `id_users` INT(255) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `nom_user` VARCHAR(200) NOT NULL,
  `prenom_user` VARCHAR(200) NOT NULL,
  `description_users` TEXT NOT NULL,
  `preference_echange` TEXT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `rights` VARCHAR(255) NOT NULL,
  `signup_date` DATE NOT NULL,
  `avatar` TEXT NOT NULL,
  `sexe` TEXT NULL DEFAULT NULL,
  `tel` TEXT NULL DEFAULT NULL,
  `situation` TEXT NULL DEFAULT NULL,
  `profession` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = MyISAM
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `welchome`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`commentaires` (
  `id_commentaire` INT(11) NOT NULL AUTO_INCREMENT,
  `date_commentaire` DATE NOT NULL,
  `id_user` INT(11) NOT NULL,
  `commentaire` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `groupe_commentaire` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`id_commentaire`, `users_id_users`),
  INDEX `fk_commentaires_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_commentaires_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`contrainte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`contrainte` (
  `id_contrainte` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_contrainte` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description_contrainte` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_contrainte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`echange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`echange` (
  `id_echange` INT(11) NOT NULL AUTO_INCREMENT,
  `id_demandeur` INT(11) NULL DEFAULT NULL,
  `id_proprietaire` INT(11) NULL DEFAULT NULL,
  `id_logement` INT(11) NULL DEFAULT NULL,
  `date_update` DATETIME NULL DEFAULT '2014-01-01 00:00:00',
  `user1` INT(11) NULL DEFAULT NULL,
  `user2` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_echange`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`favoris` (
  `id_favoris` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NULL DEFAULT NULL,
  `nom_favoris` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `id_logement` INT(11) NOT NULL,
  `id_ami` INT(11) NULL DEFAULT NULL,
  `friend` INT(11) NULL DEFAULT NULL,
  `users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`id_favoris`, `users_id_users`),
  INDEX `fk_favoris_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_favoris_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`forum_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`forum_forum` (
  `id_cat` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_cat` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `nb_message` INT(11) NOT NULL,
  `last_message` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`forum_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`forum_topic` (
  `id_topic` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cat` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL,
  `nom_topic` TEXT NOT NULL,
  `topic_first_post` TEXT NOT NULL,
  `nb_answer` INT(11) NOT NULL,
  `nb_views` INT(11) NOT NULL,
  `priority_topic` INT(11) NULL DEFAULT NULL,
  `users_id_users` INT(255) NOT NULL,
  `forum_forum_id_cat` INT(11) NOT NULL,
  PRIMARY KEY (`id_topic`, `users_id_users`, `forum_forum_id_cat`),
  INDEX `fk_forum_topic_users1_idx` (`users_id_users` ASC),
  INDEX `fk_forum_topic_forum_forum1_idx` (`forum_forum_id_cat` ASC),
  CONSTRAINT `fk_forum_topic_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_topic_forum_forum1`
    FOREIGN KEY (`forum_forum_id_cat`)
    REFERENCES `welchome`.`forum_forum` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`forum_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`forum_post` (
  `id_post` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_topic` INT(11) NOT NULL,
  `texte_post` TEXT NOT NULL,
  `users_id_users` INT(255) NOT NULL,
  `forum_topic_id_topic` INT(11) NOT NULL,
  `forum_topic_users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`id_post`, `users_id_users`, `forum_topic_id_topic`, `forum_topic_users_id_users`),
  INDEX `fk_forum_post_users1_idx` (`users_id_users` ASC),
  INDEX `fk_forum_post_forum_topic1_idx` (`forum_topic_id_topic` ASC, `forum_topic_users_id_users` ASC),
  CONSTRAINT `fk_forum_post_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_post_forum_topic1`
    FOREIGN KEY (`forum_topic_id_topic` , `forum_topic_users_id_users`)
    REFERENCES `welchome`.`forum_topic` (`id_topic` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`logement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`logement` (
  `id_logement` INT(11) NOT NULL AUTO_INCREMENT,
  `id_users` INT(11) NOT NULL,
  `localisation` TEXT NOT NULL,
  `type_endroit` VARCHAR(200) NOT NULL,
  `nom_maison` TEXT NOT NULL,
  `nombre_voyageurs` INT(11) NULL DEFAULT NULL,
  `type_logement` LONGTEXT NULL DEFAULT NULL,
  `nb_chambres` INT(11) NOT NULL,
  `nb_salles_bains` INT(11) NOT NULL,
  `superficie` INT(11) NOT NULL,
  `description_logement` TEXT NOT NULL,
  `attributs_logement` TEXT NOT NULL,
  `date_début_disponibilite` DATE NOT NULL,
  `date_fin_disponibilite` DATE NOT NULL,
  `date_publication_logement` DATE NOT NULL,
  `television` INT(11) NULL DEFAULT NULL,
  `machine_a_laver` INT(11) NULL DEFAULT NULL,
  `parking` INT(11) NULL DEFAULT NULL,
  `climatisation` INT(11) NULL DEFAULT NULL,
  `piscine` INT(11) NULL DEFAULT NULL,
  `jardin` INT(11) NULL DEFAULT NULL,
  `numero_logement` INT(11) NULL DEFAULT NULL,
  `users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`id_logement`, `users_id_users`),
  INDEX `fk_logement_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_logement_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `welchome`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`messages` (
  `id_message` INT(11) NOT NULL AUTO_INCREMENT,
  `id_expediteur` INT(11) NOT NULL DEFAULT '0',
  `id_destinataire` INT(11) NOT NULL DEFAULT '0',
  `date_update` DATETIME NULL DEFAULT '2014-01-01 00:00:00',
  `titre_message` TEXT CHARACTER SET 'utf8' NOT NULL,
  `message` TEXT CHARACTER SET 'utf8' NOT NULL,
  `lu_nonlu` INT(11) NULL DEFAULT NULL,
  `echange` INT(11) NULL DEFAULT NULL,
  `choix` INT(11) NULL DEFAULT NULL,
  `users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`id_message`, `users_id_users`),
  INDEX `fk_messages_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`photo` (
  `id_photo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_logement` INT(11) NOT NULL,
  `lien_photo` VARCHAR(800) CHARACTER SET 'utf8' NOT NULL,
  `chemin_photo` VARCHAR(255) NOT NULL,
  `logement_id_logement` INT(11) NOT NULL,
  `logement_users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`id_photo`, `logement_id_logement`, `logement_users_id_users`),
  INDEX `fk_photo_logement1_idx` (`logement_id_logement` ASC, `logement_users_id_users` ASC),
  CONSTRAINT `fk_photo_logement1`
    FOREIGN KEY (`logement_id_logement` , `logement_users_id_users`)
    REFERENCES `welchome`.`logement` (`id_logement` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`services` (
  `id_service` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_services` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description_services` TEXT CHARACTER SET 'utf8' NOT NULL,
  `id_logement` INT(11) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`contrainte_has_logement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`contrainte_has_logement` (
  `contrainte_id_contrainte` INT(11) NOT NULL,
  `logement_id_logement` INT(11) NOT NULL,
  `logement_users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`contrainte_id_contrainte`, `logement_id_logement`, `logement_users_id_users`),
  INDEX `fk_contrainte_has_logement_logement1_idx` (`logement_id_logement` ASC, `logement_users_id_users` ASC),
  INDEX `fk_contrainte_has_logement_contrainte1_idx` (`contrainte_id_contrainte` ASC),
  CONSTRAINT `fk_contrainte_has_logement_contrainte1`
    FOREIGN KEY (`contrainte_id_contrainte`)
    REFERENCES `welchome`.`contrainte` (`id_contrainte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrainte_has_logement_logement1`
    FOREIGN KEY (`logement_id_logement` , `logement_users_id_users`)
    REFERENCES `welchome`.`logement` (`id_logement` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `welchome`.`logement_has_services1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`logement_has_services1` (
  `logement_id_logement` INT(11) NOT NULL,
  `logement_users_id_users` INT(255) NOT NULL,
  `services_id_service` INT(11) NOT NULL,
  PRIMARY KEY (`logement_id_logement`, `logement_users_id_users`, `services_id_service`),
  INDEX `fk_logement_has_services1_services1_idx` (`services_id_service` ASC),
  INDEX `fk_logement_has_services1_logement1_idx` (`logement_id_logement` ASC, `logement_users_id_users` ASC),
  CONSTRAINT `fk_logement_has_services1_logement1`
    FOREIGN KEY (`logement_id_logement` , `logement_users_id_users`)
    REFERENCES `welchome`.`logement` (`id_logement` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logement_has_services1_services1`
    FOREIGN KEY (`services_id_service`)
    REFERENCES `welchome`.`services` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `welchome`.`echange_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `welchome`.`echange_has_users` (
  `echange_id_echange` INT(11) NOT NULL,
  `users_id_users` INT(255) NOT NULL,
  PRIMARY KEY (`echange_id_echange`, `users_id_users`),
  INDEX `fk_echange_has_users_users1_idx` (`users_id_users` ASC),
  INDEX `fk_echange_has_users_echange1_idx` (`echange_id_echange` ASC),
  CONSTRAINT `fk_echange_has_users_echange1`
    FOREIGN KEY (`echange_id_echange`)
    REFERENCES `welchome`.`echange` (`id_echange`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_echange_has_users_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `welchome`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
